version: 2.1

executors:
  ubuntu-default:
    machine: 
      image: ubuntu-2204:current
    resource_class: medium

jobs:
  test-prereqs:
    executor: ubuntu-default
    steps:
      - checkout
      - run: 
          name: test init script for ubuntu
          command: sh install_prereqs_machine.sh

  test-prereqs-param:
    executor: ubuntu-default
    environment:
       HELM_VERSION: "v3.15.0"
       TERRAFORM_VERSION: "1.8.3"
    steps:
      - checkout
      - run: 
          name: test parameterized init script for ubuntu
          command: sh install_prereqs_parameterized.sh

workflows:
  main:
    jobs:
      - test-prereqs
      - test-prereqs-param
